apiVersion: v1
kind: Service
metadata:
  name: podinfo-service
  labels:
    app: podinfo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9898
      protocol: TCP
  selector:
    app: podinfo
